#ifndef __ELLYZ__RL_PONG__CONSTANTS__
#define __ELLYZ__RL_PONG__CONSTANTS__

#define GAME_NAME "Raylib Pong"
#define START_WIDTH 800
#define START_HEIGHT 500
#define BACKGROUND_COLOR ((Color) { 220, 220, 220, 225 })

#define BOUNDARY_PADDING 20
#define BOUNDARY_THICKNESS 20
#define BOUNDARY_INCREATE_RATE 0
#define BOUNDARY_COLOR ((Color) { 50, 50, 50, 255 })

#define SCORE_SIZE_PROPORTION 0.7
#define SCORE_COLOR ((Color) { 50, 50, 50, 70 })

#define PLAYER_VELOCITY 0.01f
#define PLAYER_SIZE_PROPORTION 0.2f
#define PLAYER_POSITION_PROPORTION 0.5f
#define PLAYER_THICKNESS 15
#define PLAYER_DASH_COOLDOWN 5.0f
#define PLAYER_DASH_VELOCITY 0.05f
#define PLAYER_DASH_DURATION 0.125f

#endif//__ELLYZ__RL_PONG__CONSTANTS__
